// v3d-specific driconf options

DRI_CONF_SECTION_MISCELLANEOUS
   DRI_CONF_V3D_NONMSAA_TEXTURE_SIZE_LIMIT(false)
   DRI_CONF_V3D_MAINTAIN_IGNORABLE_SCANOUT(false)
   DRI_CONF_V3D_IGNORE_SCANOUT_USAGES_WITH_MODIFIERS(false)
DRI_CONF_SECTION_END
